from .core import (
    Device,
    is_gpu_available,
    sync,
    Tensor,
    tensor,
    matmul,
    add,
    sub,
    mul,
    div,
    relu,
    sigmoid,
    gelu,
    tanh,
    sum_tensor as sum,
    mean_tensor as mean,
    matmul_relu,
    matmul_add,
    matmul_add_relu,
    matmul_add_relu_residual,
    add_relu,
    memory_stats,
    memory_clear,
    get_device_properties,
    auto_tune_elementwise,
    auto_tune_matmul
)

from .ir import (
    OpKind,
    Value,
    Node,
    Graph,
    Pass,
    PassManager,
    ConstantFoldingPass,
    AlgebraicSimplificationPass,
    CommonSubexpressionEliminationPass,
    OperatorFusionPass,
    DeadCodeEliminationPass,
    CUDACodeGen,
    trace,
    compile,
    CompiledGraph
)

from .onnx_frontend import (
    from_onnx,
    compile_onnx
)

__version__ = "0.1.4"
__all__ = [
    "Device",
    "is_gpu_available",
    "sync",
    "Tensor",
    "tensor",
    "matmul",
    "add",
    "sub",
    "mul",
    "div",
    "relu",
    "sigmoid",
    "gelu",
    "tanh",
    "sum",
    "mean",
    "matmul_relu",
    "matmul_add",
    "matmul_add_relu",
    "matmul_add_relu_residual",
    "add_relu",
    "memory_stats",
    "memory_clear",
    "get_device_properties",
    "auto_tune_elementwise",
    "auto_tune_matmul",
    "from_onnx",
    "compile_onnx",
    "OpKind",
    "Value",
    "Node",
    "Graph",
    "Pass",
    "PassManager",
    "ConstantFoldingPass",
    "AlgebraicSimplificationPass",
    "CommonSubexpressionEliminationPass",
    "OperatorFusionPass",
    "DeadCodeEliminationPass",
    "CUDACodeGen",
    "trace",
    "compile",
    "CompiledGraph"
]
